import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {} from "next/navigation";
import { GlobalLayout } from "widgets/layouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html>
      <GlobalLayout className={inter.className}>{children}</GlobalLayout>
    </html>
  );
}
